apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gateway-service-patch.yaml

patches:
  - path: gateway-cert-issuer-patch.yaml
    target:
      kind: Gateway
      name: internal-gateway
