site_name: K8TRE
site_description: SATRE-Compliant TRE implementation on Kubernetes
site_author: K8TRE Team
repo_url: https://github.com/umccr/k8tre
repo_name: k8tre/k8tre

theme:
  name: material
  logo: img/logo.jpeg
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - macros
extra_css:
  - css/colour-blocks.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Specification:
      - Introduction: spec/README.md
      - Glossary: spec/glossary.md
      - The K8TRE Specification:
        #  - Asset Management : spec/assetmanagement.md
          - BYO Software : spec/byosoftware.md
          - Container Runtimes : spec/containerruntimes.md
          - Databases : spec/database.md
          - DNS : spec/dns.md
          - Documentation : spec/documentation.md
        #  - Egress : spec/egress.md
          - GitOps : spec/gitops.md
          - Identity: spec/identity.md
          - Ingress : spec/ingress.md
          - Networking : spec/networking.md
        #  - Resources : spec/resources.md
          - Secrets : spec/secrets.md
          - Storage : spec/storage.md
          - Workspace Isolation: spec/workspaceisolation.md
  - Implementation:
      - Infrastructure: implementation/architecture.md
      - ArgoCD: implementation/argocd.md
      - Agnostics: implementation/agnostics.md
      - Applications: implementation/applications.md
      - Network Policy: implementation/network-policy.md
  # - Deployment:
  #     - Installation: deployment/installation.md
  - Development:
      - Introduction: development/introduction.md
      - K3S Single-Cluster Setup: development/k3s-dev.md
      - K3S Multi-Cluster Setup: development/k3s.md
      - Application Development: development/developer-guide.md
  - Guides:
      - Installation: guides/installation.md
      - Workspace Access: guides/workspace-access.md
  - Contributing: contributing.md
