apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - selfsigned-clusterissuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.18.0
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
