guacamole:
  image:
    repository: ghcr.io/k8tre/guacamole-json
    tag: "v1.0.0"
    pullPolicy: Always
  env:
    - name: GUACAMOLE_HOME
      value: /etc/guacamole
    - name: GUACD_HOSTNAME
      value: guacamole-guacd
    - name: GUACD_PORT
      value: "4822"

ingress:
  enabled: false
