apiVersion: v1
kind: ConfigMap
metadata:
  name: k8tre-realm-config
  namespace: keycloak
data:
  realm-name: k8tre-app
  realm-display-name: Karectl Application Realm
  keycloak-url: "https://keycloak.k8tre.${ENVIRONMENT}.${DOMAIN}/"
  keycloak-verify-tls: "true"
