apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

# See https://www.keycloak.org/operator/installation#_installing_multiple_operators
resources:
  - certificate.yaml
  - keycloak-db-external-secret.yaml
  - keycloak-admin-external-secret.yaml
  - keycloak-realm-config.yaml
  - gateway-route.yaml
  - postgres.yaml

#patches:
#  - path: projects-patch.yaml

helmCharts:
  - name: keycloakx
    repo: https://codecentric.github.io/helm-charts
    version: 7.1.3
    releaseName: keycloak
    namespace: keycloak
    valuesFile: values.yaml
