apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: keycloak-config
    literals:
      - ENVIRONMENT=${ENVIRONMENT}
      - DOMAIN=${DOMAIN}
  - name: keycloak-realm-config
    files:
      - realm.json=keycloak-realm-config.json

generatorOptions:
  disableNameSuffixHash: true
