postgresql:
  enabled: false
externalDatabase:
  host: keycloak-postgres-cluster-rw
  database: keycloak
  port: 5432
  existingSecret: keycloak-db-secret # pragma: allowlist secret
  existingSecretUserKey: username # pragma: allowlist secret
  existingSecretPasswordKey: password # pragma: allowlist secret
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.dev.k8tre.internal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: keycloak.dev.k8tre.internal
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  tls: true
  extraTls:
    - secretName: keycloak-k8tre-tls # pragma: allowlist secret
      hosts:
        - keycloak.dev.k8tre.internal
auth:
  adminUser: admin
  existingSecret: keycloak-admin-secret # pragma: allowlist secret
  passwordSecretKey: admin-password # pragma: allowlist secret

logging:
  level: DEBUG
