serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::843407916570:role/eksctl-k8tre-dev-addon-iamserviceaccount-exte-Role1-42XcRCaBgtPt

policy: sync
provider:
  name: aws
  env:
    - name: AWS_DEFAULT_REGION
      value: ap-southeast-2
