controller:
  publishService:
    enabled: "true" # This is required for external-dns to work
  service:
    annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
