apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: letsencrypt-issuer-patch.yaml
    target:
      kind: ClusterIssuer
      name: letsencrypt-ca
