fullnameOverride: external-dns

serviceAccount:
  create: true
  name: external-dns
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "da830846-717d-4957-8315-e260999e743f"

podLabels:
  azure.workload.identity/use: "true"

extraVolumes:
  - name: azure-config-file
    secret:
      secretName: external-dns-azure # pragma: allowlist secret

extraVolumeMounts:
  - name: azure-config-file
    mountPath: /etc/kubernetes
    readOnly: true

provider:
  name: azure-private-dns

policy: sync
txtOwnerId: external-dns

domainFilters:
  - dev.k8tre.org
